version: "3"
services:

  mysql:
    container_name: abiola-mysqldb
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: abiola123
      MYSQL_DATABASE: springThymeleaf
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: